/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lapr.project.controller.RegistarCandidaturaController;
import lapr.project.model.ListaProdutos;
import lapr.project.model.Produto;

/**
 *
 * @author Fábio Sousa
 */
public class ProdutosUI extends javax.swing.JDialog {
    private JFrame framePai;
    private ModeloListaProdutos modelProdutct;
    private RegistarCandidaturaController controller;
    private ListaProdutos listaProdutos;
    /**
     * Creates new form Produtos
     */
    public ProdutosUI(JFrame parent, boolean modal,RegistarCandidaturaController controller) {
        super(parent, modal);
        this.framePai=parent;
        this.listaProdutos =new ListaProdutos();
        this.listaProdutos.getListaProdutos();
        initComponents();
        
        this.jListProdutos.setModel(modelProdutct);
        this.controller=controller;
        setVisible(true);
        setLocationRelativeTo(framePai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddProduto = new javax.swing.JButton();
        RemoveProduto = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Confirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProdutos = new javax.swing.JList<>();

        AddProduto.setText("AddProduto");
        AddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdutoActionPerformed(evt);
            }
        });

        RemoveProduto.setText("removeProduto");
        RemoveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveProdutoActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoveProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProduto)
                    .addComponent(RemoveProduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jListProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdutoActionPerformed
        if(listaProdutos.tamanho()<5){
        JOptionPane.showInputDialog("Insira um produto....");
}else{
    JOptionPane.showMessageDialog(null, "Não pode inserir mais de 0 produtos!", "Inserir um produto", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_AddProdutoActionPerformed

    private void RemoveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveProdutoActionPerformed
        List<Produto> produtosRemover = new ArrayList<>((List<Produto>)jListProdutos.getSelectedValuesList());

        if (listaProdutos.tamanho() == 0) {
            JOptionPane.showMessageDialog(ProdutosUI.this,
                    "Seleccione um produto!",
                    "Eliminar produto",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            String[] itens = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(ProdutosUI.this,
                    "Eliminar\n" + produtosRemover.toString(),
                    "Eliminar Produto",
                    0,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    itens,
                    itens[1]);
            final int SIM = 0;
            if (resposta == SIM) {
                ModeloListaProdutos modeloLista
                        = (ModeloListaProdutos) jListProdutos.getModel();
                for (Produto str : produtosRemover) {
                    modeloLista.removeElement(str);

                }
            }
        }
    }//GEN-LAST:event_RemoveProdutoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
                                             
        framePai.setVisible(true);
        dispose();
      
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
         if(modelProdutct.getSize()>0){
        String[] opSimNao = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(ProdutosUI.this,
                "Tem a certeza que quer confirmar a lista com um total de " + modelProdutct.getSize() + " palavras-chave?",
                "Confirmar Lista de Produtos",
                0,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opSimNao,
                opSimNao[1]);

        final int SIM = 0;
        if (resposta == SIM) {
            AddProduto.setEnabled(false);
            RemoveProduto.setEnabled(false);
            Confirmar.setEnabled(false);

        }
        }else{
            JOptionPane.showMessageDialog(ProdutosUI.this,"É necessário que a lista de palavras-chave possua pelo menos um autor para que seja confirmada!","Confirmar Lista de Palavras-Chave",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduto;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton RemoveProduto;
    private javax.swing.JButton Voltar;
    private javax.swing.JList<Produto> jListProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
